# Generated by Django 4.2.2 on 2025-06-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('manzil', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=20)),
                ('faoliyat_turi', models.CharField(max_length=100)),
                ('ochilgan_sana', models.DateField()),
                ('ishchi_soni', models.IntegerField()),
                ('qayta_ishlaydigan_materiallar', models.TextField()),
                ('izoh', models.TextField(blank=True)),
            ],
        ),
    ]
